create table institutes (
  id bigint generated by default as identity primary key,
  name text not null,
  short_name text
);

create table buildings (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique, -- 'У', 'А', 'С'
  address text
);

create table rooms (
  id bigint generated by default as identity primary key,
  building_id bigint references buildings(id) on delete cascade,
  room_number text not null, -- '408', '504'
  unique(building_id, room_number)
);

create table subjects (
  id bigint generated by default as identity primary key,
  name text not null unique -- 'Физика', 'Матан'
);

create table groups (
  id bigint generated by default as identity primary key,
  name text not null unique, -- '609-51'
  course int not null,
  institute_id bigint references institutes(id)
);

create table roles (
  id bigint generated by default as identity primary key,
  name text not null unique -- 'Студент', 'Преподаватель'
);

create table users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  
  -- Уведомления
  telegram_id text unique,
  email text unique,
  
  -- Инфо
  full_name text not null, -- Для преподов парсим из Excel сюда
  role_id bigint not null references roles(id),
  phone_number text unique,
  
  -- Студенческое
  group_id bigint references groups(id),
  subgroup int CHECK (subgroup IN (1, 2))
);

-- РАСПИСАНИЕ
INSERT INTO schedule_item_statuses (id, name, color) VALUES 
(9, 'Активно', '#00FF00'), 
(10, 'Отменено', '#FF0000')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

SELECT setval(pg_get_serial_sequence('schedule_item_statuses', 'id'), (SELECT MAX(id) FROM schedule_item_statuses));

INSERT INTO schedule_item_statuses (name, color) VALUES 
('Активно', '#00FF00'),    -- ID 1
('Отменено', '#FF0000'); -- ID 2

create table schedule_items (
  id bigint generated by default as identity primary key,
  
  -- Связи
  subject_id bigint references subjects(id),
  speaker_id bigint references users(id), -- Тот, кто ведет лекцию / мероприятие
  room_id bigint references rooms(id),
  
  -- Группировка (важно для Excel!)
  group_id bigint references groups(id), -- Каждая запись Excel привязана к группе
  subgroup int, -- NULL = вся группа, 1 = первая подгруппа, 2 = вторая
  
  -- Время
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,

  -- Детали
  title text, -- название мероприятия / тип пары ('лек', 'пр', 'лаб')
  description text, -- "Защита лабораторных", "Будет в Teams"
  is_lesson boolean default true, -- false для мероприятий
  
  status bigint references schedule_item_statuses(id),
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

create table event_participants (
  schedule_item_id bigint references schedule_items(id) on delete cascade,
  user_id bigint references users(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique(schedule_item_id, user_id) -- Один юзер не может зарегистрироваться дважды
);

create table schedule_changes (
  id bigint generated by default as identity primary key,
  schedule_item_id bigint references schedule_items(id),
  changed_by bigint references users(id), -- кто админ
  old_values jsonb, -- {"room_id": 5, "start_time": "..."}
  new_values jsonb,
  created_at timestamp with time zone default now()
);

create table teacher_workload (
  id bigint generated by default as identity primary key,
  teacher_id bigint references users(id) on delete cascade,
  subject_id bigint references subjects(id) on delete cascade,
  
  -- Нагрузка (в академических часах)
  planned_hours int not null check (planned_hours > 0),
  
  -- Период: храним только год начала (например, 2025)
  start_year int not null check (start_year > 2020 and start_year < 2100),
  semester int not null check (semester in (1, 2)), 
  
  -- Составной ключ
  unique(teacher_id, subject_id, start_year, semester)
);

-- Поиск по группе (главный юзкейс)
create index idx_schedule_items_group on schedule_items(group_id, start_time);

-- Поиск по преподу
create index idx_schedule_items_speaker on schedule_items(speaker_id, start_time);

-- Поиск по аудитории (проверка конфликтов)
create index idx_schedule_items_room on schedule_items(room_id, start_time);

-- Поиск по времени (календарь)
create index idx_schedule_items_time on schedule_items(start_time, end_time);

-- Telegram ID для бота
create index idx_users_telegram on users(telegram_id) where telegram_id is not null;

-- Поиск юзера по телефону (регистрация)
create index idx_users_phone on users(phone_number);

create index idx_workload_teacher_year_sem on teacher_workload(teacher_id, start_year, semester);

-- Функция для авто-обновления
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Триггер на schedule_items
create trigger set_updated_at
before update on schedule_items
for each row
execute function update_updated_at_column();

create extension if not exists btree_gist;

-- Constraint: преподаватель не может вести два занятия одновременно
ALTER TABLE schedule_items
ADD CONSTRAINT no_teacher_overlap
EXCLUDE USING gist (
  speaker_id WITH =,
  tstzrange(start_time, end_time) WITH &&
)
WHERE (speaker_id IS NOT NULL AND status = 9); -- status должен быть равен айдишнику статуса Активно

-- Constraint: одна аудитория не может быть занята одновременно
ALTER TABLE schedule_items
ADD CONSTRAINT no_room_overlap
EXCLUDE USING gist (
  room_id WITH =,
  tstzrange(start_time, end_time) WITH &&
)
WHERE (room_id IS NOT NULL AND status = 9);

-- Constraint: группа не может быть на двух парах одновременно
ALTER TABLE schedule_items
ADD CONSTRAINT no_group_overlap
EXCLUDE USING gist (
  group_id WITH =,
  COALESCE(subgroup, 0) WITH =,
  tstzrange(start_time, end_time) WITH &&
)
WHERE (group_id IS NOT NULL AND is_lesson = true AND status = 9);

create index idx_schedule_items_workload_calc 
on schedule_items(speaker_id, subject_id, start_time) 
where is_lesson = true;

-- Функция для обновления нагрузки
create or replace function update_workload_hours()
returns trigger as $$
declare
  -- Определяем длительность пары в академических часах (обычно 2 часа)
  -- Можно усложнить и считать разницу start_time/end_time, но для MVP хватит константы
  ac_hours int := 2; 
  is_cancelled boolean;
begin
  -- 1. ПРИ СОЗДАНИИ ПАРЫ (INSERT)
  if (TG_OP = 'INSERT') then
    -- Если пара активна (не отменена), вычитаем часы
    if NEW.status = (select id from schedule_item_statuses where name = 'Активно' limit 1) then
      update teacher_workload
      set planned_hours = planned_hours - ac_hours
      where teacher_id = NEW.speaker_id 
        and subject_id = NEW.subject_id
        and start_year = extract(year from NEW.start_time)::int; -- Упрощаем год
    end if;
    return NEW;
  end if;

  -- 2. ПРИ ОБНОВЛЕНИИ (UPDATE)
  if (TG_OP = 'UPDATE') then
    -- Получаем ID статуса "отменено"
    is_cancelled := (NEW.status = (select id from schedule_item_statuses where name = 'Отменено' limit 1));
    
    -- Сценарий А: Пару ОТМЕНИЛИ (была активна -> стала cancelled)
    if OLD.status != NEW.status and is_cancelled then
      update teacher_workload
      set planned_hours = planned_hours + ac_hours
      where teacher_id = NEW.speaker_id 
        and subject_id = NEW.subject_id;
    end if;

    -- Сценарий Б: Пару ВОССТАНОВИЛИ (была cancelled -> стала active)
    if OLD.status != NEW.status and not is_cancelled then
      update teacher_workload
      set planned_hours = planned_hours - ac_hours
      where teacher_id = NEW.speaker_id 
        and subject_id = NEW.subject_id;
    end if;
    
    return NEW;
  end if;

  return null;
end;
$$ language plpgsql;

-- Создаем триггер
create trigger trg_update_workload
after insert or update on schedule_items
for each row
execute function update_workload_hours();


-- Добавляем жесткое ограничение
ALTER TABLE teacher_workload 
ADD CONSTRAINT check_hours_positive CHECK (planned_hours >= 0);